name: '🔎 Super-Linter'

on:
  push:
    branches:
      - main
      - cicd-setup
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - 'release-please*'

jobs:
  super-lint:
    name: 'Super-Linter Checks'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SUPER_LINTER_TOKEN }}

      - name: Run Super-Linter
        uses: github/super-linter@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: .git|node_modules
